### ISSUE TITLE
Question: Implementation of “Sign in with Tezos”.

### ISSUE THREAD

**Issue by dansan566** [walt-id/waltid-nftkit#109]
Hey Team, 

I just read the article "[Open Source NFT Infrastructure For Developers And Businesses Building On Tezos](https://xtz.news/nft-news/open-source-nft-infrastructure-for-developers-and-businesses-building-on-tezos/)" and want to ask if you use the [SIWT](https://github.com/stakenow/siwt) (Sign in with Tezos) open source library? The article mentions the following: "on top of that, developers can also verify users’ ownership of a wallet with an implementation of “Sign in with Tezos”." If yes, we would like to add the walt.id logo to siwt.xyz with your permission! 

Best regards,
Daniel

**Comment by philpotisk** [comment]
Hey @dansan566 thanks for reaching out to us! Based on https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-122.md we have implemented SIWT our selves. Some docs can be found here here https://docs.walt.id/v/idpkit/concepts/identity-provision-via-nfts-with-tezos/sign-in-with-tezos-siwt

**Comment by jdsika** [comment]
Hello @philpotisk 
In the context of the GaiaX 4 PLC-AAD project we are using the [SIWT](https://github.com/StakeNow/SIWT/) open source library as a common resource in order to avoid the reimplementation of the features. Thank you for pointing out the reference to chain agnostic - I personally was not aware of those improvement proposals. I would be happy to get in touch with the author of the Sing in with X proposal.
We could schedule a quick meeting to get aligned and see if we have topic overlaps? carlo.van-driesten@bmw.de

Best regards
Carlo
